# Generated by Django 5.2.5 on 2025-08-13 20:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RocketStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('power_status', models.CharField(choices=[('OFF', 'Power Off'), ('ON', 'Power On'), ('LAUNCHED', 'Launched'), ('ABORTED', 'Aborted')], default='OFF', max_length=10)),
                ('launch_initiated', models.DateTimeField(blank=True, null=True)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='LaunchLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('action', models.CharField(max_length=50)),
                ('details', models.TextField()),
                ('rocket', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='propursion.rocketstatus')),
            ],
        ),
        migrations.CreateModel(
            name='TelemetryData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('mass', models.FloatField(help_text='Mass in kg')),
                ('roll', models.FloatField(help_text='Roll angle in degrees')),
                ('pitch', models.FloatField(help_text='Pitch angle in degrees')),
                ('yaw', models.FloatField(help_text='Yaw angle in degrees')),
                ('temperature', models.FloatField(help_text='Temperature in °C')),
                ('pressure', models.FloatField(help_text='Pressure in kPa')),
                ('acceleration', models.FloatField(help_text='Acceleration in m/s²')),
                ('speed', models.FloatField(help_text='Speed in m/s')),
                ('altitude', models.FloatField(help_text='Altitude in meters')),
                ('gps_position', models.CharField(help_text='GPS coordinates (lat,long)', max_length=50)),
                ('x_sensor_safe_status', models.BooleanField(help_text='Sensor safety status')),
                ('rocket', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='telemetry_data', to='propursion.rocketstatus')),
            ],
        ),
    ]
